events {}

http {
    upstream items_backend {
        server items-svc-s14:8161;
    }

    upstream notify_backend {
        server notify-svc-s14:8170;
    }

    server {
        listen 80;

        location /api/items {
            proxy_pass http://items_backend/items;
        }

        location /api/notify {
            proxy_pass http://notify_backend/notify;
        }

        location /health {
            proxy_pass http://items_backend/health;
        }
    }
}
