# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: items.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'items.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bitems.proto\x12\x08items.v1\"-\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\".\n\x11\x43reateItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\t\"\x1c\n\x0eGetItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\":\n\x11UpdateItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\"\x1f\n\x11\x44\x65leteItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x12\x44\x65leteItemResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x12\n\x10ListItemsRequest\"2\n\x11ListItemsResponse\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.items.v1.Item2\xc8\x02\n\x0cItemsService\x12\x39\n\nCreateItem\x12\x1b.items.v1.CreateItemRequest\x1a\x0e.items.v1.Item\x12\x33\n\x07GetItem\x12\x18.items.v1.GetItemRequest\x1a\x0e.items.v1.Item\x12\x44\n\tListItems\x12\x1a.items.v1.ListItemsRequest\x1a\x1b.items.v1.ListItemsResponse\x12\x39\n\nUpdateItem\x12\x1b.items.v1.UpdateItemRequest\x1a\x0e.items.v1.Item\x12G\n\nDeleteItem\x12\x1b.items.v1.DeleteItemRequest\x1a\x1c.items.v1.DeleteItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'items_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=25
  _globals['_ITEM']._serialized_end=70
  _globals['_CREATEITEMREQUEST']._serialized_start=72
  _globals['_CREATEITEMREQUEST']._serialized_end=118
  _globals['_GETITEMREQUEST']._serialized_start=120
  _globals['_GETITEMREQUEST']._serialized_end=148
  _globals['_UPDATEITEMREQUEST']._serialized_start=150
  _globals['_UPDATEITEMREQUEST']._serialized_end=208
  _globals['_DELETEITEMREQUEST']._serialized_start=210
  _globals['_DELETEITEMREQUEST']._serialized_end=241
  _globals['_DELETEITEMRESPONSE']._serialized_start=243
  _globals['_DELETEITEMRESPONSE']._serialized_end=275
  _globals['_LISTITEMSREQUEST']._serialized_start=277
  _globals['_LISTITEMSREQUEST']._serialized_end=295
  _globals['_LISTITEMSRESPONSE']._serialized_start=297
  _globals['_LISTITEMSRESPONSE']._serialized_end=347
  _globals['_ITEMSSERVICE']._serialized_start=350
  _globals['_ITEMSSERVICE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
