# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\nreviews.v1\"2\n\x06Review\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x05\"3\n\x13\x43reateReviewRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x05\"\x1e\n\x10GetReviewRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x14\n\x12ListReviewsRequest\":\n\x13ListReviewsResponse\x12#\n\x07reviews\x18\x01 \x03(\x0b\x32\x12.reviews.v1.Review2\xe4\x01\n\x0eReviewsService\x12\x43\n\x0c\x43reateReview\x12\x1f.reviews.v1.CreateReviewRequest\x1a\x12.reviews.v1.Review\x12=\n\tGetReview\x12\x1c.reviews.v1.GetReviewRequest\x1a\x12.reviews.v1.Review\x12N\n\x0bListReviews\x12\x1e.reviews.v1.ListReviewsRequest\x1a\x1f.reviews.v1.ListReviewsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REVIEW']._serialized_start=29
  _globals['_REVIEW']._serialized_end=79
  _globals['_CREATEREVIEWREQUEST']._serialized_start=81
  _globals['_CREATEREVIEWREQUEST']._serialized_end=132
  _globals['_GETREVIEWREQUEST']._serialized_start=134
  _globals['_GETREVIEWREQUEST']._serialized_end=164
  _globals['_LISTREVIEWSREQUEST']._serialized_start=166
  _globals['_LISTREVIEWSREQUEST']._serialized_end=186
  _globals['_LISTREVIEWSRESPONSE']._serialized_start=188
  _globals['_LISTREVIEWSRESPONSE']._serialized_end=246
  _globals['_REVIEWSSERVICE']._serialized_start=249
  _globals['_REVIEWSSERVICE']._serialized_end=477
# @@protoc_insertion_point(module_scope)
