# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReviewsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateReview = channel.unary_unary(
                '/reviews.v1.ReviewsService/CreateReview',
                request_serializer=service__pb2.CreateReviewRequest.SerializeToString,
                response_deserializer=service__pb2.Review.FromString,
                _registered_method=True)
        self.GetReview = channel.unary_unary(
                '/reviews.v1.ReviewsService/GetReview',
                request_serializer=service__pb2.GetReviewRequest.SerializeToString,
                response_deserializer=service__pb2.Review.FromString,
                _registered_method=True)
        self.ListReviews = channel.unary_unary(
                '/reviews.v1.ReviewsService/ListReviews',
                request_serializer=service__pb2.ListReviewsRequest.SerializeToString,
                response_deserializer=service__pb2.ListReviewsResponse.FromString,
                _registered_method=True)


class ReviewsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateReview': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReview,
                    request_deserializer=service__pb2.CreateReviewRequest.FromString,
                    response_serializer=service__pb2.Review.SerializeToString,
            ),
            'GetReview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReview,
                    request_deserializer=service__pb2.GetReviewRequest.FromString,
                    response_serializer=service__pb2.Review.SerializeToString,
            ),
            'ListReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReviews,
                    request_deserializer=service__pb2.ListReviewsRequest.FromString,
                    response_serializer=service__pb2.ListReviewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reviews.v1.ReviewsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reviews.v1.ReviewsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReviewsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reviews.v1.ReviewsService/CreateReview',
            service__pb2.CreateReviewRequest.SerializeToString,
            service__pb2.Review.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reviews.v1.ReviewsService/GetReview',
            service__pb2.GetReviewRequest.SerializeToString,
            service__pb2.Review.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reviews.v1.ReviewsService/ListReviews',
            service__pb2.ListReviewsRequest.SerializeToString,
            service__pb2.ListReviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
