# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0bsessions.v1\"/\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\"0\n\x14\x43reateSessionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"\x1f\n\x11GetSessionRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x18SubscribeSessionsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"D\n\rSessionUpdate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\r\n\x05\x65vent\x18\x04 \x01(\t2\xf9\x01\n\x0fSessionsService\x12H\n\rCreateSession\x12!.sessions.v1.CreateSessionRequest\x1a\x14.sessions.v1.Session\x12\x42\n\nGetSession\x12\x1e.sessions.v1.GetSessionRequest\x1a\x14.sessions.v1.Session\x12X\n\x11SubscribeSessions\x12%.sessions.v1.SubscribeSessionsRequest\x1a\x1a.sessions.v1.SessionUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSION']._serialized_start=30
  _globals['_SESSION']._serialized_end=77
  _globals['_CREATESESSIONREQUEST']._serialized_start=79
  _globals['_CREATESESSIONREQUEST']._serialized_end=127
  _globals['_GETSESSIONREQUEST']._serialized_start=129
  _globals['_GETSESSIONREQUEST']._serialized_end=160
  _globals['_SUBSCRIBESESSIONSREQUEST']._serialized_start=162
  _globals['_SUBSCRIBESESSIONSREQUEST']._serialized_end=203
  _globals['_SESSIONUPDATE']._serialized_start=205
  _globals['_SESSIONUPDATE']._serialized_end=273
  _globals['_SESSIONSSERVICE']._serialized_start=276
  _globals['_SESSIONSSERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
